#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4cvs on Sat Aug  6 00:28:38 2005
#
# ArabicAnalyzer
# Copyright (C) 2005 Alexander Lee
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import wx
from AnalyzerFrame import AnalyzerFrame
from AnalyzerFrame import LoadAnalyzerEvent

class ArabicAnalyzer(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        analyzerFrame = AnalyzerFrame(None, -1, "")
        self.SetTopWindow(analyzerFrame)
        analyzerFrame.Show()

        loadEvent = LoadAnalyzerEvent(analyzerFrame.GetId())
        analyzerFrame.AddPendingEvent(loadEvent)
        return 1

# end of class ArabicAnalyzer

# Run the program
if __name__ == "__main__":
    ArabicAnalyzer = ArabicAnalyzer(0)
    ArabicAnalyzer.MainLoop()
